# Generated by Django 5.0.6 on 2024-07-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('terrains', models.CharField(max_length=255)),
                ('climates', models.CharField(max_length=255)),
            ],
        ),
    ]
